"""CP-2: hook command strings are cmd.exe-safe on Windows, valid on POSIX."""
from __future__ import annotations

import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "scripts" / "install"))
import hookcmd  # noqa: E402

EVENTS = ["SessionStart", "UserPromptSubmit", "Stop", "SessionEnd"]
VAULT = pathlib.Path("/Users/dev/hera vault")  # a path with a space, on purpose


def test_windows_has_no_posixisms():
    for ev in EVENTS:
        cmd = hookcmd.hook_command("nt", VAULT, ev)
        assert not hookcmd.has_posixisms(cmd), f"{ev}: posixism in {cmd!r}"
        assert "&&" not in cmd
        assert "$" not in cmd
        assert not cmd.lstrip().startswith(". ")


def test_windows_points_at_venv_python_exe():
    cmd = hookcmd.hook_command("nt", VAULT, "SessionStart")
    assert r"\.venv\Scripts\python.exe" in cmd
    assert r"\.claude\hooks\session_start.py" in cmd
    # No forward slashes in the Windows form.
    assert "/" not in cmd


def test_windows_paths_are_quoted():
    # The vault has a space; both tokens must be double-quoted.
    cmd = hookcmd.hook_command("nt", VAULT, "Stop")
    assert cmd.count('"') == 4  # two quoted tokens


def test_posix_form():
    cmd = hookcmd.hook_command("posix", VAULT, "UserPromptSubmit")
    assert "/.venv/bin/python" in cmd
    assert "/.claude/hooks/prompt_inject.py" in cmd
    # POSIX form generated by us is also clean: no source, no &&, no $VAR.
    assert not hookcmd.has_posixisms(cmd)


def test_every_event_maps_to_a_script():
    for ev in EVENTS:
        assert ev in hookcmd.HOOK_SCRIPTS


def test_has_posixisms_detector():
    assert hookcmd.has_posixisms('. "$HOME/x.env" && "y" "z"')
    assert hookcmd.has_posixisms('"a" && "b"')
    assert hookcmd.has_posixisms('"$HERA_VAULT/py" "hook"')
    assert not hookcmd.has_posixisms('"C:\\v\\py.exe" "C:\\v\\hook.py"')
